### ISSUE TITLE
Plugin fails to load images

### ISSUE THREAD

**Issue by polarbearing** [JOSM/Mapillary#48]
Since I recently updated JOSM (and thereby most likely the plugin), the sequences load and show up, but the images do not. 
```
JOSM/1.5 (11926 en) Mac OS X 10.11.6
Memory Usage: 1416 MB / 3641 MB (334 MB allocated, but free)
Java version: 1.8.0_111-b14, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
+ Mapillary (v1.5.1)
```

Once I mouse-over or click an image node, java throws an event as below. After working while having the mapillary layer on, JOSM freezes and needs to be killed. 
```
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at javax.swing.JPopupMenu.show(JPopupMenu.java:948)
	at org.openstreetmap.josm.plugins.mapillary.gui.imageinfo.ImageInfoHelpPopup.showPopup(ImageInfoHelpPopup.java:77)
	at org.openstreetmap.josm.plugins.mapillary.gui.MapillaryMainDialog.updateImage(MapillaryMainDialog.java:209)
	at org.openstreetmap.josm.plugins.mapillary.gui.MapillaryMainDialog.updateImage(MapillaryMainDialog.java:185)
	at org.openstreetmap.josm.plugins.mapillary.mode.SelectMode.mouseMoved(SelectMode.java:181)
	at java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:330)
```
etc.

Tracing versions, the problem started when I upgraded to JOSM 11879 on Apr 10, before that I was running 11604 with mapillary working fine.

**Comment by polarbearing** [comment]
Dup of [JOSM ticket](https://josm.openstreetmap.de/ticket/14627)

**Comment by floscher** [comment]
0e141af800c430122b3a9df3e72c2f79bb9ed8ef fixes this problem.
The latest release [v1.5.2](https://github.com/JOSM/Mapillary/releases/v1.5.2) contains the fix, so it should now work again.

**Comment by M1dgard** [comment]
Not fixed.

Running v1.5.2:

![notfixed](https://cloud.githubusercontent.com/assets/4283376/25097111/66206ea6-23a3-11e7-95da-1dc78e3bc32c.gif)

**Comment by floscher** [comment]
I'm sorry, this was introduced by me in 8961dd036871cfe115c14a76c6db2b1d151293db.
I changed how the download URLs are generated and unintentionally changed the `.jpg` file extension to `.png`. Because of that, no new images are downloaded, only cached images are shown.

I'm currently preparing a hotfix release, which will fix this issue.

The issue previously reported here is technically unrelated and should really already be fixed.

**Comment by floscher** [comment]
@M1dgard Ok, [version `1.5.3`](https://github.com/JOSM/Mapillary/releases/v1.5.3) is now released as a hotfix release and will shortly be available to all JOSM users. It contains the fix for this problem.

**Comment by polarbearing** [comment]
1.5.2:
Yes, while I don't get ```java.awt.IllegalComponentStateException``` anymore, I get error 403 from the cloud server:
```INFO: GET https://d1cuyjsrcm0gby.cloudfront.net/.../thumb-320.png -> 403```
1.5.3
works:
INFO: GET https://....cloudfront.net/.../thumb-2048.jpg -> 200 (632 kB)

**Comment by floscher** [comment]
@polarbearing Exactly, sorry for the inconvenience. That's what happens, when I release software without adding accompanying unit tests.
