### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by don-vip** [JOSM/Mapillary#82]
We have 19 unit tests failing:

https://josm.openstreetmap.de/jenkins/job/Java-EarlyAccess-JOSM-Plugins/79/jdk=JDK12/testReport/

All with the same stacktrace:
```
junit.framework.AssertionFailedError: modifiers
	at org.openstreetmap.josm.plugins.mapillary.utils.TestUtil.getAccessibleField(TestUtil.java:40)
	at org.openstreetmap.josm.plugins.mapillary.io.download.SequenceDownloadRunnableTest.setUp(SequenceDownloadRunnableTest.java:39)
	at org.openstreetmap.josm.testutils.JOSMTestRules$TimeoutThread.run(JOSMTestRules.java:700)
```

**Comment by floscher** [comment]
Thank you for reporting, this has to do with reflective access to private fields in unit tests. Probably something has been changed in Java 12 that does no longer allow certain access. I already saw a deprecation warning when compiling with Java 10 in that part of the code.

https://github.com/JOSM/Mapillary/blob/7774170b187c3dc0ec3601a301afc3f80eaa3a99/test/unit/org/openstreetmap/josm/plugins/mapillary/utils/TestUtil.java#L32-L42

I will take a look and see what I can do.

**Comment by floscher** [comment]
Just for reference:
It seems like Java is now carrying out what they already warn about when compiling with Java 10:
```
> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openstreetmap.josm.plugins.mapillary.utils.TestUtil (file:/builds/JOSM/Mapillary/build/classes/java/test/) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.openstreetmap.josm.plugins.mapillary.utils.TestUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
  🏁 Finished after 38.83 seconds.
```
(excerpt of https://gitlab.com/JOSM/Mapillary/-/jobs/101974395)

**Comment by don-vip** [comment]
Can you please log the stacktrace instead of just displaying the localized message? We don't know what exact exception is raised.

**Comment by floscher** [comment]
I'm removing the whole method, so this won't be a problem anymore.

**Comment by floscher** [comment]
This should be solved in https://github.com/JOSM/Mapillary/commit/3cce61d27796cb8779e131788408d1227f0ac138#diff-8f6c53a4b886fcd4f27f7eeeeadc0fd6L31 .

**Comment by don-vip** [comment]
Thanks! I have relaunched manually a build: https://josm.openstreetmap.de/jenkins/job/Java-EarlyAccess-JOSM-Plugins/80/

**Comment by don-vip** [comment]
Much better, only two issues remaining:
https://josm.openstreetmap.de/jenkins/job/Java-EarlyAccess-JOSM-Plugins/lastCompletedBuild/jdk=JDK12/testReport/

**Comment by floscher** [comment]
Yes, [one has to do with WireMock](https://josm.openstreetmap.de/jenkins/job/Java-EarlyAccess-JOSM-Plugins/80/jdk=JDK12/testReport/org.openstreetmap.josm.plugins.mapillary.io.download/SequenceDownloadRunnableTest/testRun2/), where I forgot to add a stub for a certain URL, that's easy to fix.

[The other one](https://josm.openstreetmap.de/jenkins/job/Java-EarlyAccess-JOSM-Plugins/80/jdk=JDK12/testReport/org.openstreetmap.josm.plugins.mapillary.model/MapObjectTest/testIcon/) looks to me as if the unit tests can't access resources for classes from the main source set, in this case an image located in `src/main/resources/images`. @don-vip : Is there something I can add to [`build.xml`](https://github.com/JOSM/Mapillary/blob/4102fd3ea48169e9642002247b9c146b39c12edc/build.xml) that adds `src/main/resources/` to the test classpath?

I'll reopen this, until it's completely resolved.

**Comment by don-vip** [comment]
I just have added a new property in [build-common.xml](https://trac.openstreetmap.org/changeset/34677/subversion)

So now you simply need to add:
```xml
<property name="plugin.resources.dir" value="src/main/resources"/>
```

**Comment by floscher** [comment]
Thanks! I now pushed e2df796a32319f955df08cf83f89f4c699c47f19...5d8911cff6fd55b30ea58797b11c32699950f866 , which should fix the failing tests.
